<?xml version="1.0" encoding="utf-8"?><Database Name="FishMarketDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ROGSTRIX\SQLEXPRESS;Initial Catalog=FishMarketDB;Integrated Security=True" SettingsObjectName="LogForm.Properties.Settings" SettingsPropertyName="FishMarketDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProductType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WholesalePrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="KeepTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdditionalNotes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>